export const ACCOUNT = 'ACCOUNT';
export const LIKED = 'LIKED';
export const LISTINGS = 'LISTINGS';
export const LOGIN = 'LOGIN';
export const MAIN = 'MAIN';
export const POST_DETAILS = 'POST_DETAILS';
export const POST_EDIT = 'POST_EDIT';

export const FEED = 'FEED';
export const FIND = 'FIND';
export const MANAGE = 'MANAGE';
export const FIND_HOME = 'FIND_HOME';
export const VIEW_MORE = 'VIEW_MORE';
export const NEARBY = 'NEARBY';
export const POSTED = 'POSTED';

// manage
export const APARTMENT_DETAILS = 'APARTMENT_DETAILS';
export const APARTMENTS = 'APARTMENTS';
export const BILLING = 'BILLING';
export const CONTRACTS = 'CONTRACTS';
export const ROOM_DETAILS = 'ROOM_DETAILS';
export const ROOMS = 'ROOMS';
export const SERVICES = 'SERVICES';
export const TENANT = 'TENANT';
export const TENANT_EDIT = 'TENANT_EDIT';
export const UTIL = 'UTIL';
export const MANAGE_HOME = 'MANAGE_HOME';
export const SEARCH = 'SEARCH';
export const NEARBY_MAP_SCREEN = 'NEARBY_MAP_SCREEN';
export const NEARBY_LIST_SCREEN = 'NEARBY_LIST_SCREEN';

//
export const APARTMENT_EDIT_SCREEN = 'APARTMENT_EDIT_SCREEN';
export const SERVICE_EDIT_SCREEN = 'SERVICE_EDIT_SCREEN';
export const ROOM_EDIT_SCREEN = 'ROOM_EDIT_SCREEN';
export const ROOM_TENANTS_SCREEN = 'ROOM_TENANTS_SCREEN';
export const CONTRACT_EDIT_SCREEN = 'CONTRACT_EDIT_SCREEN';
export const CONTRACT_ACTIVE_SCREEN = 'CONTRACT_ACTIVE_SCREEN';
export const CONTRACT_TERMINATED_SCREEN = 'CONTRACT_TERMINATED_SCREEN';
export const CONTRACT_EXPIRED_SCREEN = 'CONTRACT_EXPIRED_SCREEN';
export const ACTIVE_SERVICE_ROOMS_SCREEN = 'ACTIVE_SERVICE_ROOMS_SCREEN';
export const CLOSED_SERVICE_ROOMS_SCREEN = 'CLOSED_SERVICE_ROOMS_SCREEN';
export const SERVICE_CLOSING = 'SERVICE_CLOSING';
export const SERVICE_CLOSING_EDIT_SCREEN = 'SERVICE_CLOSING_EDIT_SCREEN';
