export default [
  { provinceId: '01', name: 'Thành phố Hà Nội' },
  { provinceId: '02', name: 'Tỉnh Hà Giang' },
  { provinceId: '04', name: 'Tỉnh Cao Bằng' },
  { provinceId: '06', name: 'Tỉnh Bắc Kạn' },
  { provinceId: '08', name: 'Tỉnh Tuyên Quang' },
  { provinceId: '10', name: 'Tỉnh Lào Cai' },
  { provinceId: '11', name: 'Tỉnh Điện Biên' },
  { provinceId: '12', name: 'Tỉnh Lai Châu' },
  { provinceId: '14', name: 'Tỉnh Sơn La' },
  { provinceId: '15', name: 'Tỉnh Yên Bái' },
  { provinceId: '17', name: 'Tỉnh Hoà Bình' },
  { provinceId: '19', name: 'Tỉnh Thái Nguyên' },
  { provinceId: '20', name: 'Tỉnh Lạng Sơn' },
  { provinceId: '22', name: 'Tỉnh Quảng Ninh' },
  { provinceId: '24', name: 'Tỉnh Bắc Giang' },
  { provinceId: '25', name: 'Tỉnh Phú Thọ' },
  { provinceId: '26', name: 'Tỉnh Vĩnh Phúc' },
  { provinceId: '27', name: 'Tỉnh Bắc Ninh' },
  { provinceId: '30', name: 'Tỉnh Hải Dương' },
  { provinceId: '31', name: 'Thành phố Hải Phòng' },
  { provinceId: '33', name: 'Tỉnh Hưng Yên' },
  { provinceId: '34', name: 'Tỉnh Thái Bình' },
  { provinceId: '35', name: 'Tỉnh Hà Nam' },
  { provinceId: '36', name: 'Tỉnh Nam Định' },
  { provinceId: '37', name: 'Tỉnh Ninh Bình' },
  { provinceId: '38', name: 'Tỉnh Thanh Hóa' },
  { provinceId: '40', name: 'Tỉnh Nghệ An' },
  { provinceId: '42', name: 'Tỉnh Hà Tĩnh' },
  { provinceId: '44', name: 'Tỉnh Quảng Bình' },
  { provinceId: '45', name: 'Tỉnh Quảng Trị' },
  { provinceId: '46', name: 'Tỉnh Thừa Thiên Huế' },
  { provinceId: '48', name: 'Thành phố Đà Nẵng' },
  { provinceId: '49', name: 'Tỉnh Quảng Nam' },
  { provinceId: '51', name: 'Tỉnh Quảng Ngãi' },
  { provinceId: '52', name: 'Tỉnh Bình Định' },
  { provinceId: '54', name: 'Tỉnh Phú Yên' },
  { provinceId: '56', name: 'Tỉnh Khánh Hòa' },
  { provinceId: '58', name: 'Tỉnh Ninh Thuận' },
  { provinceId: '60', name: 'Tỉnh Bình Thuận' },
  { provinceId: '62', name: 'Tỉnh Kon Tum' },
  { provinceId: '64', name: 'Tỉnh Gia Lai' },
  { provinceId: '66', name: 'Tỉnh Đắk Lắk' },
  { provinceId: '67', name: 'Tỉnh Đắk Nông' },
  { provinceId: '68', name: 'Tỉnh Lâm Đồng' },
  { provinceId: '70', name: 'Tỉnh Bình Phước' },
  { provinceId: '72', name: 'Tỉnh Tây Ninh' },
  { provinceId: '74', name: 'Tỉnh Bình Dương' },
  { provinceId: '75', name: 'Tỉnh Đồng Nai' },
  { provinceId: '77', name: 'Tỉnh Bà Rịa - Vũng Tàu' },
  { provinceId: '79', name: 'Thành phố Hồ Chí Minh' },
  { provinceId: '80', name: 'Tỉnh Long An' },
  { provinceId: '82', name: 'Tỉnh Tiền Giang' },
  { provinceId: '83', name: 'Tỉnh Bến Tre' },
  { provinceId: '84', name: 'Tỉnh Trà Vinh' },
  { provinceId: '86', name: 'Tỉnh Vĩnh Long' },
  { provinceId: '87', name: 'Tỉnh Đồng Tháp' },
  { provinceId: '89', name: 'Tỉnh An Giang' },
  { provinceId: '91', name: 'Tỉnh Kiên Giang' },
  { provinceId: '92', name: 'Thành phố Cần Thơ' },
  { provinceId: '93', name: 'Tỉnh Hậu Giang' },
  { provinceId: '94', name: 'Tỉnh Sóc Trăng' },
  { provinceId: '95', name: 'Tỉnh Bạc Liêu' },
  { provinceId: '96', name: 'Tỉnh Cà Mau' },
];
